global using MiniPOSSystemWithRepositoryDesignPattern.Models.Admin;
global using MiniPOSSystemWithRepositoryDesignPattern.Utils;
global using Microsoft.EntityFrameworkCore;
global using MiniPOSSystemWithRepositoryDesignPattern.Database.Models;
global using MiniPOSSystemWithRepositoryDesignPattern.Models.Product;
global using MiniPOSSystemWithRepositoryDesignPattern.Models.ProductCategory;
global using MiniPOSSystemWithRepositoryDesignPattern.Models.Sale;
global using MiniPOSSystemWithRepositoryDesignPattern.Models.Invoice;

